name: Scheduled Task

on:
  schedule:
    - cron: '*/5 * * * *'  # This means every minute

jobs:
  run-task:
    runs-on: ubuntu-latest  # GitHub's cloud environment
    steps:
      - name: Trigger Render Server
        run: curl -X POST https://agrierp-backand-server.onrender.com
